### PR TITLE
flake: bump stable to 24.11

### PR DESCRIPTION
**Pull request by Thatoo**
move stable from 24.05 to 24.11

### CODE REVIEW

**Review by lilyinstarlight — CHANGES_REQUESTED** [review]
This needs at least a lockfile update to be mergable (and I will untangle rust-overlay stuff when bumping to 24.11 myself)

I'm also still wary of bumping away from a stable branch to a still-unstable branch before 24.11 is released, but I also don't feel strongly either way

**Comment by Thatoo** [comment]
Hurray! 24.11 has been released. https://nixos.org/blog/announcements/2024/nixos-2411/

**Comment by drakon64** [comment]
I'm currently running COSMIC on 24.11 and it seems to be fine, no regressions from 24.05 that I can see

**Comment by lilyinstarlight** [comment]
This still needs lockfile updates as requested, but I'll just manually push to this branch so that it can be ready for merge

**Review by lilyinstarlight — APPROVED** [review]

**Comment by lilyinstarlight** [comment]
CI broke so I spent the evening building and uploading closures to cachix, woo. All done now so I'm merging

**Pull request merged**
